"""Shared constants for the large Swarm Air-Defense OpenSpiel game."""
from __future__ import annotations

import itertools
from typing import List, Sequence, Tuple

ARENA_WIDTH = 32.0
ARENA_HEIGHT = 32.0
BOTTOM_START = ARENA_HEIGHT * 0.5
NUM_TARGETS = 3
NUM_AD_UNITS = 2
NUM_ATTACKING_DRONES = 40
NUM_INTERCEPTORS = NUM_ATTACKING_DRONES // 2
DRONE_SPEED = 1.0
INTERCEPTOR_SPEED_MULTIPLIER = 2.0
ENTRY_LANES = 24
ENTRY_POINTS: List[Tuple[float, float]] = [(0.0, lane + 0.5) for lane in range(ENTRY_LANES)]
LARGE_TOT_CHOICES: Tuple[float, ...] = (0.0, 1.5, 3.0, 4.5)
AD_COVERAGE_RADIUS = 5.5
AD_KILL_RATE = 0.05
AD_MIN_EFFECTIVE_EXPOSURE = 0.75
INTERCEPTOR_LAUNCH_ROW = ARENA_HEIGHT + 2.0
INTERCEPTOR_KILL_PROB = 0.95
DRONE_VS_AD_KILL_PROB = 0.8
DRONE_VS_TARGET_KILL_PROB = 0.7
RRT_TIME_LIMIT_SEC = 0.035

TARGET_CANDIDATE_CELLS: List[Tuple[float, float]] = [
    (row, col)
    for row in [12.0, 14.5, 17.0, 19.5, 22.0]
    for col in [3.0, 7.0, 11.0, 15.0, 19.0]
]
TARGET_VALUE_OPTIONS: Tuple[float, ...] = (10.0, 25.0, 60.0)
TARGET_VALUE_PERMUTATIONS: List[Sequence[int]] = list(itertools.permutations(range(NUM_TARGETS)))

AD_POSITION_CANDIDATES: List[Tuple[float, float]] = [
    (row, col)
    for row in [13.0, 15.5, 18.0, 20.5]
    for col in [2.5, 6.5, 10.5, 14.5, 18.5]
]

DRONE_TARGET_SLOTS = NUM_TARGETS + NUM_AD_UNITS
MIDPOINT_OPTIONS = 4

TARGET_POSITION_ACTIONS = len(TARGET_CANDIDATE_CELLS)
TARGET_VALUE_ACTIONS = len(TARGET_VALUE_PERMUTATIONS)
AD_PLACEMENT_ACTIONS = len(AD_POSITION_CANDIDATES)
DRONE_ASSIGNMENT_ACTIONS = ENTRY_LANES * DRONE_TARGET_SLOTS * len(LARGE_TOT_CHOICES) * MIDPOINT_OPTIONS
INTERCEPT_CHOICES = NUM_ATTACKING_DRONES + 1

TARGET_POSITION_ACTION_BASE = 0
TARGET_VALUE_ACTION_BASE = TARGET_POSITION_ACTION_BASE + TARGET_POSITION_ACTIONS
AD_ACTION_BASE = TARGET_VALUE_ACTION_BASE + TARGET_VALUE_ACTIONS
DRONE_ACTION_BASE = AD_ACTION_BASE + AD_PLACEMENT_ACTIONS
INTERCEPT_ACTION_BASE = DRONE_ACTION_BASE + DRONE_ASSIGNMENT_ACTIONS
AD_RESOLVE_ACTION_BASE = INTERCEPT_ACTION_BASE + INTERCEPT_CHOICES
NUM_DISTINCT_ACTIONS = AD_RESOLVE_ACTION_BASE + 2

__all__ = [
    "ARENA_WIDTH",
    "ARENA_HEIGHT",
    "BOTTOM_START",
    "NUM_TARGETS",
    "NUM_AD_UNITS",
    "NUM_ATTACKING_DRONES",
    "NUM_INTERCEPTORS",
    "DRONE_SPEED",
    "INTERCEPTOR_SPEED_MULTIPLIER",
    "ENTRY_LANES",
    "ENTRY_POINTS",
    "LARGE_TOT_CHOICES",
    "AD_COVERAGE_RADIUS",
    "AD_KILL_RATE",
    "AD_MIN_EFFECTIVE_EXPOSURE",
    "INTERCEPTOR_LAUNCH_ROW",
    "INTERCEPTOR_KILL_PROB",
    "DRONE_VS_AD_KILL_PROB",
    "DRONE_VS_TARGET_KILL_PROB",
    "RRT_TIME_LIMIT_SEC",
    "TARGET_CANDIDATE_CELLS",
    "TARGET_VALUE_OPTIONS",
    "TARGET_VALUE_PERMUTATIONS",
    "AD_POSITION_CANDIDATES",
    "DRONE_TARGET_SLOTS",
    "MIDPOINT_OPTIONS",
    "TARGET_POSITION_ACTIONS",
    "TARGET_VALUE_ACTIONS",
    "AD_PLACEMENT_ACTIONS",
    "DRONE_ASSIGNMENT_ACTIONS",
    "INTERCEPT_CHOICES",
    "TARGET_POSITION_ACTION_BASE",
    "TARGET_VALUE_ACTION_BASE",
    "AD_ACTION_BASE",
    "DRONE_ACTION_BASE",
    "INTERCEPT_ACTION_BASE",
    "AD_RESOLVE_ACTION_BASE",
    "NUM_DISTINCT_ACTIONS",
]
